hostname pe1
log file /tmp/pe1/frr.log
debug bgp neighbor-events
debug bgp updates
debug bgp zebra
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor 2001:db8:1::2 remote-as 65000
 neighbor 2001:db8:2::2 remote-as 65002
 !
 address-family ipv4 mup
  neighbor 2001:db8:1::2 activate
  neighbor 2001:db8:2::2 activate
 exit-address-family
 !
 address-family ipv6 mup
  neighbor 2001:db8:1::2 activate
  neighbor 2001:db8:2::2 activate
 exit-address-family
exit
