hostname gw1
log file /tmp/gw1/frr.log
debug bgp neighbor-events
debug bgp updates
debug bgp zebra
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor 2001:db8:1::2 remote-as 65001
 !
 segment-routing srv6
  locator default
 exit
 !
 address-family ipv4 mup
  neighbor 2001:db8:1::2 activate
  segment interwork 10.99.0.0/24 rd 200:200 rt 10:10
 exit-address-family
exit
