hostname pe1
no zebra nexthop kernel enable
debug zebra kernel
debug zebra rib detailed
debug zebra dplane detailed
!
segment-routing
 srv6
  locators
   locator default
    prefix 2001:db8:e::/48 block-len 24 node-len 24 func-bits 8
   exit
  exit
 exit
exit
